Enhancement/skale 2466 sign hash
skalenetwork/transaction-manager pull request #33
Opened 2020-04-27 19:29 UTC by DmytroNazarenko

* Add sign_hash
* Add sign_hash tests

2020-04-27 20:02 UTC, dmytrotkk requested changes

2020-04-27 20:02 UTC, dmitry-tk commented on server.py
> +    # # r + s + v
remove debug code

2020-04-28 08:28 UTC, badrogger commented on server.py
> +    # # r + s + v
Let's leave it for now

2020-04-28 09:02 UTC, dmytrotkk approved these changes

2020-04-28 09:12 UTC, badrogger approved these changes

2020-04-28 09:12 UTC, merged