Fix/skale 2801 nonce too low
skalenetwork/transaction-manager pull request #74
Opened 2020-06-29 21:54 UTC by badrogger

2020-06-30 09:51 UTC, dmytrotkk requested changes
tests failed

2020-07-08 14:32 UTC, dmitry-tk commented
Tests fixed, nonce works fine now 🙃

2020-07-08 14:32 UTC, dmytrotkk approved these changes

2020-07-08 15:01 UTC, badrogger commented on main.py
> +    logger.info(f'thread_id: {threading.get_ident()}, waiting for the lock')
Why context manager was removed ?

2020-07-08 15:01 UTC, badrogger commented on tests/server_test.py
> +        thread = CustomThread(
I think using regular Thread will be enough in this case

2020-07-09 08:42 UTC, dmitry-tk commented on main.py
> +    logger.info(f'thread_id: {threading.get_ident()}, waiting for the lock')
returned context manager

2020-07-09 08:51 UTC, merged